### ISSUE TITLE
update with iob-soc master

### ISSUE THREAD

**Issue by jjts** [IObundle/iob-soc-sha#13]
seems to be somewhat behind

I see long lists of axi4 signals signals which can be simplified by including stubs from iob-interconnect. More stubs can be created in iob-interconnect if needed

**Comment by P-Miranda** [comment]
`milestone 2` branch is already updated with iob-soc master branch (`commit 316575e` from 24 October, one of the most recent master branch commits from iob-soc which passed automatic checks).
See PR #10
